package com.spring.security.poc.entity;
// Generated Dec 8, 2017 7:45:03 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpOrganizationUsersId generated by hbm2java
 */
@Embeddable
public class SpOrganizationUsersId implements java.io.Serializable {

	private int orgId;
	private int userId;
	private Integer isPrimary;

	public SpOrganizationUsersId() {
	}

	public SpOrganizationUsersId(int orgId, int userId) {
		this.orgId = orgId;
		this.userId = userId;
	}

	public SpOrganizationUsersId(int orgId, int userId, Integer isPrimary) {
		this.orgId = orgId;
		this.userId = userId;
		this.isPrimary = isPrimary;
	}

	@Column(name = "org_id", nullable = false)
	public int getOrgId() {
		return this.orgId;
	}

	public void setOrgId(int orgId) {
		this.orgId = orgId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "is_primary")
	public Integer getIsPrimary() {
		return this.isPrimary;
	}

	public void setIsPrimary(Integer isPrimary) {
		this.isPrimary = isPrimary;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpOrganizationUsersId))
			return false;
		SpOrganizationUsersId castOther = (SpOrganizationUsersId) other;

		return (this.getOrgId() == castOther.getOrgId()) && (this.getUserId() == castOther.getUserId())
				&& ((this.getIsPrimary() == castOther.getIsPrimary()) || (this.getIsPrimary() != null
						&& castOther.getIsPrimary() != null && this.getIsPrimary().equals(castOther.getIsPrimary())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrgId();
		result = 37 * result + this.getUserId();
		result = 37 * result + (getIsPrimary() == null ? 0 : this.getIsPrimary().hashCode());
		return result;
	}

}
