package com.spring.security.poc.entity;
// Generated Dec 8, 2017 7:45:03 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SpOrganizationUsers generated by hbm2java
 */
@Entity
@Table(name = "sp_organization_users", catalog = "spring_security_poc")
public class SpOrganizationUsers implements java.io.Serializable {

	private SpOrganizationUsersId id;
	private SpOrganization spOrganization;
	private SpUsers spUsers;

	public SpOrganizationUsers() {
	}

	public SpOrganizationUsers(SpOrganizationUsersId id, SpOrganization spOrganization, SpUsers spUsers) {
		this.id = id;
		this.spOrganization = spOrganization;
		this.spUsers = spUsers;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orgId", column = @Column(name = "org_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "isPrimary", column = @Column(name = "is_primary")) })
	public SpOrganizationUsersId getId() {
		return this.id;
	}

	public void setId(SpOrganizationUsersId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id", nullable = false, insertable = false, updatable = false)
	public SpOrganization getSpOrganization() {
		return this.spOrganization;
	}

	public void setSpOrganization(SpOrganization spOrganization) {
		this.spOrganization = spOrganization;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public SpUsers getSpUsers() {
		return this.spUsers;
	}

	public void setSpUsers(SpUsers spUsers) {
		this.spUsers = spUsers;
	}

}
