package com.spring.security.poc.entity;
// Generated Dec 8, 2017 7:45:03 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpPermissionMappingId generated by hbm2java
 */
@Embeddable
public class SpPermissionMappingId implements java.io.Serializable {

	private int roleId;
	private int permissionId;

	public SpPermissionMappingId() {
	}

	public SpPermissionMappingId(int roleId, int permissionId) {
		this.roleId = roleId;
		this.permissionId = permissionId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "permission_id", nullable = false)
	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpPermissionMappingId))
			return false;
		SpPermissionMappingId castOther = (SpPermissionMappingId) other;

		return (this.getRoleId() == castOther.getRoleId()) && (this.getPermissionId() == castOther.getPermissionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getPermissionId();
		return result;
	}

}
