package com.spring.security.poc.entity;
// Generated Dec 8, 2017 7:45:03 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SpRoles generated by hbm2java
 */
@Entity
@Table(name = "sp_roles", catalog = "spring_security_poc")
public class SpRoles implements java.io.Serializable {

	private Integer id;
	private String name;
	private String displayName;
	private String createdBy;
	private Date createdOn;
	private String updatedBy;
	private Date updatedOn;
	private Set<SpPermissionMapping> spPermissionMappings = new HashSet<SpPermissionMapping>(0);
	private Set<SpRoleMapping> spRoleMappings = new HashSet<SpRoleMapping>(0);
	private Set<SpPermissionMapping> spPermissionMappings_1 = new HashSet<SpPermissionMapping>(0);
	private Set<SpRoleMapping> spRoleMappings_1 = new HashSet<SpRoleMapping>(0);

	public SpRoles() {
	}

	public SpRoles(String name, String displayName, String createdBy, Date createdOn, String updatedBy, Date updatedOn,
			Set<SpPermissionMapping> spPermissionMappings, Set<SpRoleMapping> spRoleMappings,
			Set<SpPermissionMapping> spPermissionMappings_1, Set<SpRoleMapping> spRoleMappings_1) {
		this.name = name;
		this.displayName = displayName;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.spPermissionMappings = spPermissionMappings;
		this.spRoleMappings = spRoleMappings;
		this.spPermissionMappings_1 = spPermissionMappings_1;
		this.spRoleMappings_1 = spRoleMappings_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "display_name", length = 100)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "created_by", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "updated_by", length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 19)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spRoles")
	public Set<SpPermissionMapping> getSpPermissionMappings() {
		return this.spPermissionMappings;
	}

	public void setSpPermissionMappings(Set<SpPermissionMapping> spPermissionMappings) {
		this.spPermissionMappings = spPermissionMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spRoles")
	public Set<SpRoleMapping> getSpRoleMappings() {
		return this.spRoleMappings;
	}

	public void setSpRoleMappings(Set<SpRoleMapping> spRoleMappings) {
		this.spRoleMappings = spRoleMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spRoles")
	public Set<SpPermissionMapping> getSpPermissionMappings_1() {
		return this.spPermissionMappings_1;
	}

	public void setSpPermissionMappings_1(Set<SpPermissionMapping> spPermissionMappings_1) {
		this.spPermissionMappings_1 = spPermissionMappings_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spRoles")
	public Set<SpRoleMapping> getSpRoleMappings_1() {
		return this.spRoleMappings_1;
	}

	public void setSpRoleMappings_1(Set<SpRoleMapping> spRoleMappings_1) {
		this.spRoleMappings_1 = spRoleMappings_1;
	}

}
