package com.spring.security.poc.entity;
// Generated Dec 8, 2017 7:45:03 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SpRoleMapping generated by hbm2java
 */
@Entity
@Table(name = "sp_role_mapping", catalog = "spring_security_poc")
public class SpRoleMapping implements java.io.Serializable {

	private SpRoleMappingId id;
	private SpOrganization spOrganization;
	private SpRoles spRoles;
	private SpUsers spUsers;

	public SpRoleMapping() {
	}

	public SpRoleMapping(SpRoleMappingId id, SpOrganization spOrganization, SpRoles spRoles, SpUsers spUsers) {
		this.id = id;
		this.spOrganization = spOrganization;
		this.spRoles = spRoles;
		this.spUsers = spUsers;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)),
			@AttributeOverride(name = "orgId", column = @Column(name = "org_id", nullable = false)) })
	public SpRoleMappingId getId() {
		return this.id;
	}

	public void setId(SpRoleMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_id", nullable = false, insertable = false, updatable = false)
	public SpOrganization getSpOrganization() {
		return this.spOrganization;
	}

	public void setSpOrganization(SpOrganization spOrganization) {
		this.spOrganization = spOrganization;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public SpRoles getSpRoles() {
		return this.spRoles;
	}

	public void setSpRoles(SpRoles spRoles) {
		this.spRoles = spRoles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public SpUsers getSpUsers() {
		return this.spUsers;
	}

	public void setSpUsers(SpUsers spUsers) {
		this.spUsers = spUsers;
	}

}
