package com.spring.security.poc.entity;
// Generated Dec 8, 2017 7:45:03 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SpRoleMappingId generated by hbm2java
 */
@Embeddable
public class SpRoleMappingId implements java.io.Serializable {

	private int userId;
	private int roleId;
	private int orgId;

	public SpRoleMappingId() {
	}

	public SpRoleMappingId(int userId, int roleId, int orgId) {
		this.userId = userId;
		this.roleId = roleId;
		this.orgId = orgId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "org_id", nullable = false)
	public int getOrgId() {
		return this.orgId;
	}

	public void setOrgId(int orgId) {
		this.orgId = orgId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpRoleMappingId))
			return false;
		SpRoleMappingId castOther = (SpRoleMappingId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getRoleId() == castOther.getRoleId())
				&& (this.getOrgId() == castOther.getOrgId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getOrgId();
		return result;
	}

}
